### ISSUE TITLE
Don't import tasks and projects

### ISSUE THREAD

**Issue by ratnikov-in** [camptocamp/connector-jira#11]
Good day.
Error: 

```
Traceback (most recent call last):
  File "/opt/odoo/odoo11/addons/queue_job/controllers/main.py", line 97, in runjob
    self._try_perform_job(env, job)
  File "/opt/odoo/odoo11/addons/queue_job/controllers/main.py", line 61, in _try_perform_job
    job.perform()
  File "/opt/odoo/odoo11/addons/queue_job/job.py", line 466, in perform
    self.result = self.func(*tuple(self.args), **self.kwargs)
  File "/opt/odoo/odoo11/addons/connector_jira/models/jira_binding/common.py", line 47, in import_record
    importer.run(external_id, force=force)
  File "/opt/odoo/odoo11/addons/connector_jira/components/importer.py", line 323, in run
    self._import_dependencies()
  File "/opt/odoo/odoo11/addons/connector_jira/models/project_task/importer.py", line 166, in _import_dependencies
    record=jira_parent)
  File "/opt/odoo/odoo11/addons/connector_jira/components/importer.py", line 120, in _import_dependency
    component.run(external_id, record=record)
  File "/opt/odoo/odoo11/addons/connector_jira/components/importer.py", line 325, in run
    self._import(binding, **kwargs)
  File "/opt/odoo/odoo11/addons/connector_jira/models/project_task/importer.py", line 145, in _import
    if not self._is_issue_type_sync():
  File "/opt/odoo/odoo11/addons/connector_jira/models/project_task/importer.py", line 126, in _is_issue_type_sync
    jira_project_id = self.external_record['fields']['project']['id']
KeyError: 'project'
```
Webhooks install, Connect success, Issues import, in module Project Jira key and Jira Backend write

What could be the error?

**Comment by Dhrupesh** [comment]
Hello,

You have to define Project key(jira key)  and PID(jira PID) in odoo project.

Thanks,

**Comment by guewen** [comment]
It happens on Subtask issues, which was not handled properly. Should be fixed now. Be aware that we made many changes recently.
